Hotfix winning conditions
microsoft/TextWorld pull request #274
Opened 2021-08-31 20:55 UTC by MathieuTuli

I noticed the `win_condition` property as part of the Game class (found in `textworld/generator/game.py`) was calling the wrong member variable for the quests. Change made to call `win_events`, not `winning_conditions` as it previously was. 

Further, mirrored the `win_condition` property to create the analogous `fail_condition` property, if that info is ever needed by the user.

Lastly, renamed `win_condition` -> `win_conditions` and `fail_condition` -> `fail_conditions` to more accurately represent their return values, which are a list of conditions (which are in fact, `generator.game.Events`)

2021-09-01 13:31 UTC, MarcCote commented
Thanks for the PR. Can I ask what is your use case for those functions? Since there are not used anywhere else in the code, I'm very tempted to simply delete them, actually.

If you do have a use case, proper tests should be added.

2021-09-01 13:32 UTC, MarcCote requested changes

2021-09-01 13:32 UTC, MarcCote commented on textworld/generator/game.py
> +    def win_conditions(self) -> List[Collection[Proposition]]:
The typing needs to be changed too. I.e., `List[Tuple[Event]]`.

2021-09-01 13:32 UTC, MarcCote commented on textworld/generator/game.py
> +    def fail_conditions(self) -> List[Collection[Proposition]]:
The typing needs to be changed too. I.e., `List[Tuple[Event]]`.

2021-09-01 13:49 UTC, MathieuTuli commented
> Thanks for the PR. Can I ask what is your use case for those functions? Since there are not used anywhere else in the code, I'm very tempted to simply delete them, actually.
> 
> If you do have a use case, proper tests should be added.

My use case lies in some work I'm doing relating to goal-conditioned RL. Having ground truth propositional logic of goal states is a required feature. As far as I could investigate, this was is the only way to retrieve that information (please correct me if I'm wrong). Although the propositional logic return by these functions uses the game's object IDs to instead of their names, so a second ID-> name lookup is actually needed, but that's just an aside. With this second lookup, I can compare against the game's` EnvInfo.facts` set of propositions.

Regarding tests, were there any specific guidelines that needed to be followed? My use case is just as information retrieval.

2021-09-01 15:49 UTC, MarcCote commented
@MathieuTuli here's what I suggest: https://github.com/MathieuTuli/TextWorld/pull/1

2021-09-01 16:13 UTC, MathieuTuli commented
> @MathieuTuli here's what I suggest: [MathieuTuli#1](https://github.com/MathieuTuli/TextWorld/pull/1)

Agreed, I had this in mind but opted for the quick workaround, which in hindsight was the wrong decision. Merged your PR, changes should be reflected.

2021-09-01 17:05 UTC, MarcCote commented
Alright. Waiting for all the tests to pass, then I will make a minor release.

Thank you for suggesting this new feature.

2021-09-01 17:08 UTC, MarcCote commented
I just noticed the PEP8 check has failed. Here's the fix: https://github.com/MathieuTuli/TextWorld/pull/2

2021-09-01 17:09 UTC, MathieuTuli commented
> I just noticed the PEP8 check has failed. Here's the fix: [MathieuTuli#2](https://github.com/MathieuTuli/TextWorld/pull/2)

I had noticed it too, made the change directly just before you mentioned this.

2021-09-01 20:36 UTC, MarcCote commented
Just a quick update. It seems there's an issue fetching packages from inform7.com website for running the tests on Azure pipelines. I'll check tomorrow to see if that's still an issue.

2021-09-01 20:36 UTC, MarcCote approved these changes

2021-09-03 01:03 UTC, merged

2021-09-03 16:48 UTC, MarcCote commented
@MathieuTuli FYI TextWorld 1.4.4 is now released on PyPi.